# Generated by Django 5.1 on 2025-03-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Equity', 'Equity'), ('Mutual Funds', 'Mutual Funds'), ('Bonds', 'Bonds'), ('Gold', 'Gold'), ('Real Estate', 'Real Estate')], max_length=50)),
                ('percentage', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='MarketData',
        ),
        migrations.DeleteModel(
            name='Portfolio',
        ),
    ]
